import { test, expect } from '@playwright/test';
import { ResultsPage } from '../../page-objects/ResultsPage';
import { WIZARD_JOURNEYS } from '../../fixtures/wizard-journeys';

/**
 * Functional Unit: Landing Page and Gig Search
 * Integration Tests: Wizard URL Parameters → Results Filtering Logic
 * 
 * ⚠️ TEST POLICY: Do NOT add .skip() when tests fail
 * Failed tests indicate real issues that need to be addressed:
 * - Bugs in the code that need fixing
 * - Changes in behavior that need documenting  
 * - Test assertions that need updating
 * 
 * Only skip tests for documented architectural limitations or disabled features.
 * 
 * These tests verify that the URL parameters generated by the wizard
 * actually filter the results correctly on the results page.
 * 
 * Strategy: Reuse WIZARD_JOURNEYS fixtures to test the same scenarios
 * that users would experience through the wizard flow.
 */

test.describe('Wizard → Results Filtering Integration', () => {

    // Test each wizard journey's filtering logic
    WIZARD_JOURNEYS.forEach((journey) => {
        // Skip rejection journeys (they don't show results)
        if (journey.expectRejection) return;

        test(`Filtering works for: ${journey.name}`, async ({ page }) => {
            const results = new ResultsPage(page);

            // Navigate directly to results with wizard's expected params
            await results.goto(journey.expectedParams);
            await results.expectLoaded();

            // Get the actual results count
            const count = await results.resultCards.count();

            // Log for debugging
            console.log(`Journey "${journey.name}" returned ${count} results`);

            // ASSERTION 1: Results page should load without error
            await expect(results.heading).toBeVisible();

            // If there are results, verify they match the filter criteria
            if (count > 0) {
                // Sample up to 5 cards for performance
                const sampleSize = Math.min(count, 5);

                for (let i = 0; i < sampleSize; i++) {
                    const card = results.resultCards.nth(i);

                    // ASSERTION 2: Each card should be visible
                    await expect(card).toBeVisible();

                    // ASSERTION 3: Verify Budget Filtering
                    if (journey.expectedParams?.budget && journey.expectedParams.budget !== 'any') {
                        const priceText = await card.locator('.gig-price').textContent();

                        if (journey.expectedParams.budget === 'free') {
                            // Free budget: should be "Free", "£0", or "TBA" (To Be Announced)
                            expect(priceText).toMatch(/Free|£0|TBA/i);
                        } else if (journey.expectedParams.budget === 'low') {
                            // Low budget (£10-£20): Extract price and verify range
                            const priceMatch = priceText?.match(/£([\d.]+)/);
                            if (priceMatch) {
                                const price = parseFloat(priceMatch[1]);
                                expect(price).toBeGreaterThan(0);
                                expect(price).toBeLessThanOrEqual(20);
                            }
                        } else if (journey.expectedParams.budget === 'mid') {
                            // Mid budget (£20-£50)
                            const priceMatch = priceText?.match(/£([\d.]+)/);
                            if (priceMatch) {
                                const price = parseFloat(priceMatch[1]);
                                expect(price).toBeGreaterThan(20);
                                expect(price).toBeLessThanOrEqual(50);
                            }
                        } else if (journey.expectedParams.budget === 'high') {
                            // High budget (£50+)
                            const priceMatch = priceText?.match(/£([\d.]+)/);
                            if (priceMatch) {
                                const price = parseFloat(priceMatch[1]);
                                expect(price).toBeGreaterThan(50);
                            }
                        }
                    }

                    // ASSERTION 4: Verify Date Filtering (if custom date specified)
                    if (journey.expectedParams?.minDate) {
                        const dateText = await card.locator('.gig-date').textContent();
                        // Date should exist and be visible
                        expect(dateText).toBeTruthy();
                        // Note: Full date validation would require parsing the date format
                        // which varies (e.g., "Fri, 31 Dec"). For now, we verify it exists.
                    }

                    // ASSERTION 5: Verify Location/Distance Filtering
                    if (journey.expectedParams?.distance) {
                        const locationText = await card.locator('.gig-location').textContent();
                        expect(locationText).toBeTruthy();

                        // If distance is 'scotland', any Scottish location is valid
                        // If distance is 'local' or '100miles', distance should be calculated
                        // (This is hard to verify without knowing the exact coordinates,
                        // but we can at least verify the location field exists)
                    }

                    // ASSERTION 6: Verify Venue Size Filtering
                    // Note: Venue capacity is not always displayed on cards,
                    // but the filtering logic should have already applied.
                    // We trust that if results are shown, they passed the filter.
                    // This could be enhanced if capacity is added to card display.
                }
            } else {
                // No results found - this is valid for some filter combinations
                await expect(results.noResultsMessage).toBeVisible();
                console.log(`  ℹ️  No results for "${journey.name}" - valid for restrictive filters`);
            }
        });
    });

    // Additional specific filtering tests
    test.describe('Specific Filter Validations', () => {

        test('Budget: Free filter excludes paid gigs', async ({ page }) => {
            // KNOWN BUG: See BACKLOG.md #1 "Budget Filter Bug - Free - £10 Range Incorrect"
            // This test will pass once the bug is fixed in /app/gigfinder/results/page.tsx line 141
            const results = new ResultsPage(page);
            await results.goto({ budget: 'free' });
            await results.expectLoaded();

            const count = await results.resultCards.count();
            if (count > 0) {
                // Check ALL cards, not just a sample
                // TBA (To Be Announced) pricing is acceptable in free filter results
                for (let i = 0; i < count; i++) {
                    const priceText = await results.resultCards.nth(i).locator('.gig-price').textContent();
                    expect(priceText).toMatch(/Free|£0|TBA/i);
                }
            }
        });

        test('Venue Size: Small filter shows only small venues', async ({ page }) => {
            const results = new ResultsPage(page);
            await results.goto({ venueSize: 'small' });
            await results.expectLoaded();

            const count = await results.resultCards.count();
            if (count > 0) {
                // Note: We can't easily verify capacity from the card UI
                // unless capacity is displayed. This test verifies the filter
                // doesn't break the page and results are shown.
                expect(count).toBeGreaterThan(0);
            }
        });

        test('Distance: Local filter with postcode', async ({ page }) => {
            const results = new ResultsPage(page);
            await results.goto({
                distance: 'local',
                postcode: 'EH1',
                location: 'Edinburgh'
            });
            await results.expectLoaded();

            const count = await results.resultCards.count();
            // Should show results or "no results" message
            if (count === 0) {
                await expect(results.noResultsMessage).toBeVisible();
            } else {
                expect(count).toBeGreaterThan(0);
            }
        });

        test('Distance: 100 miles filter with Glasgow postcode', async ({ page }) => {
            const results = new ResultsPage(page);
            await results.goto({
                distance: '100miles',
                postcode: 'G1',
                location: 'Glasgow'
            });
            await results.expectLoaded();

            const count = await results.resultCards.count();
            if (count === 0) {
                await expect(results.noResultsMessage).toBeVisible();
            } else {
                expect(count).toBeGreaterThan(0);
            }
        });

        test('Combined filters: Free + Small + Scotland', async ({ page }) => {
            const results = new ResultsPage(page);
            await results.goto({
                budget: 'free',
                venueSize: 'small',
                distance: 'scotland'
            });
            await results.expectLoaded();

            const count = await results.resultCards.count();

            if (count > 0) {
                // Verify at least one card meets the criteria
                const firstCard = results.resultCards.first();
                const priceText = await firstCard.locator('.gig-price').textContent();
                expect(priceText).toMatch(/Free|£0|TBA/i);
            } else {
                // No results is valid for restrictive filters
                await expect(results.noResultsMessage).toBeVisible();
            }
        });

        test('Date filter: Future date shows only future events', async ({ page }) => {
            const results = new ResultsPage(page);
            const futureDate = '2026-12-31';

            await results.goto({ minDate: futureDate });
            await results.expectLoaded();

            const count = await results.resultCards.count();

            // All events should be on or after the specified date
            // (Hard to verify without parsing dates, but we verify the filter works)
            if (count === 0) {
                await expect(results.noResultsMessage).toBeVisible();
            } else {
                expect(count).toBeGreaterThan(0);
            }
        });
    });

    // Edge cases and error handling
    test.describe('Edge Cases', () => {

        test('Invalid postcode gracefully handled', async ({ page }) => {
            const results = new ResultsPage(page);
            await results.goto({
                distance: 'local',
                postcode: 'INVALID99'
            });

            // Should still load, might show no results or use default coords
            await results.expectLoaded();
            await expect(results.heading).toBeVisible();
        });

        test('No filters shows all available events', async ({ page }) => {
            const results = new ResultsPage(page);
            await results.goto({});

            await results.expectLoaded();
            const count = await results.resultCards.count();

            // Should show at least some events (assuming DB has data)
            // If no events in DB, this is still valid
            expect(count).toBeGreaterThanOrEqual(0);
        });

        test('Extremely restrictive filters may show no results', async ({ page }) => {
            const results = new ResultsPage(page);
            await results.goto({
                budget: 'high',
                venueSize: 'small',
                distance: 'local',
                postcode: 'EH1',
                minDate: '2099-12-31' // Far future
            });

            await results.expectLoaded();

            // Likely no results, but page should handle gracefully
            const count = await results.resultCards.count();
            if (count === 0) {
                await expect(results.noResultsMessage).toBeVisible();
            }
        });
    });
});
